<?php

/**
 * User activate view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tue Jun 02, 2009 07:50 AM
 */

$this->headTitle('Activate');

?>

<h1>Account Activated</h1>

<p>Thank you for registering and activating your account at moss.org.mv. The
doors have opened for you for communion and collaboration.</p>

<p><a href="<?php echo $this->baseUrl ?>/login">Login</a> at your leisure!</p>

<p>Thank you for your support!</p>
