<?php

/**
 * User Registration View.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 10:29 AM
 */

$this->headTitle('User Registration');

?>

<h1>Register</h1>

<p>By filling out the form below and prior to registering yourself, make sure
you have read the moss.org.mv Privacy Policy and the Disclaimer.</p>

<p>All the fields are <span class="required">required</span>.</p>

<p>Once completed, you should receive and email with instructions on how to
activate your newly created account at moss.org.mv. We look forward to your
participation and support.</p>

<p>You profile avatar is automatically taken from
<a href="http://gravatar.com">gravatar.com</a> which basically matches up with
the email address you provide.</p>

<?php if (isset($this->rmessages) && count($this->rmessages) > 0): ?>
<p class="error">Please correct the errors below!</p>
<?php endif; ?>

<form method="post" action="<?php echo $this->baseUrl ?>/register">
    <table border="0" cellspacing="0" cellpadding="4" align="left">
        <thead>
        </thead>
        <tbody>
            <?php if (isset($this->messages['userId']))
                echo $this->partial('index/form-error.phtml', array('message' => $this->rmessages['userId'])) ?>
            <tr>
                <th>Username:</th>
                <td><input type="text" name="userId" size="30" value="<?php echo $this->user['userId'] ?>" /></td>
            </tr>
            <?php if (isset($this->messages['name']))
                echo $this->partial('index/form-error.phtml', array('message' => $this->rmessages['name'])) ?>
            <tr>
                <th>Name:</th>
                <td><input type="text" name="name" size="30" value="<?php echo $this->user['name'] ?>" /></td>
            </tr>
            <?php if (isset($this->messages['email']))
                echo $this->partial('index/form-error.phtml', array('message' => $this->rmessages['email'])) ?>
            <tr>
                <th>Email:</th>
                <td><input type="text" name="email" size="30" value="<?php echo $this->user['email'] ?>" /></td>
            </tr>
            <?php if (isset($this->messages['password']))
                echo $this->partial('index/form-error.phtml', array('message' => $this->rmessages['password'])) ?>
            <tr>
                <th>Password:</th>
                <td>
                    <input type="password" name="password" size="20" />
                    <em>Minimum 8 characters</em>
                </td>
            </tr>
            <?php if (isset($this->messages['passwordc']))
                echo $this->partial('index/form-error.phtml', array('message' => $this->rmessages['passwordc'])) ?>
            <tr>
                <th>Confirm Password:</th>
                <td><input type="password" name="passwordc" size="20" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" name="register" value="Register" class="button-bg" />
                    <input type="reset" value="Reset" />
                </td>
            </tr>
        </tfoot>
    </table>
</form>
