<?php

/**
 * View to display the recent activity on the site from the logs table in the
 * database.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Wed Jun 10, 2009 03:50 PM
 */

$this->headTitle('Recent Activity');

?>

<h1>Recent Activity</h1>

<table border="0" cellspacing="0" cellpadding="4" class="border mini" width="640">
    <thead>
        <tr>
            <th>Date</th>
            <th>Module</th>
            <th>Code</th>
            <th>User</th>
            <th>Message</th>
        </tr>
    </thead>
    <?php foreach ($this->paginator->getCurrentItems() as $item): ?>
    <tr>
        <td><?php echo $item['timestamp'] ?></td>
        <td><?php echo $item['entity'] ?>:<?php echo $item['entityId'] ?></td>
        <td><?php echo $item['code'] ?></td>
        <td><?php echo $item['userId'] ?></td>
        <td><?php echo $item['message'] ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'index/paginator.phtml') ?>
