<?php

/**
 * Main default admin sidebar. This show's up if a user of class Administrator
 * authenticates.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Jun 08, 2009 11:52 PM
 */

?>

<h1>Admin</h1>

<ul class="ul">
    <li><a href="<?php echo $this->baseUrl ?>/admin/activity">Recent Activity</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/admin/users">Manage Users</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/admin/pages">Manage Pages</a></li>
</ul>
