<?php

/**
 * Registration process completed view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 03:29 PM
 */

$this->headTitle('Registration Complete');

?>

<h1>Registration Successful</h1>

<p>Thank you for registering at moss.org.mv.</p>

<p>However, you registration is not yet complete. You will receive an email
shortly with instructions on how to activate your account.</p>

<p>Follow the instructions to activate your account. Once activated, you will
be able to log on to moss.org.mv and join a growing community of thriving
individuals to promote and share Free and Open Source Software in the Maldives.
</p>

<p>Make sure you read our <a href="<?php echo $this->baseUrl ?>/Policies">Policies</a>
and agree to it's terms.</p>

<p><a href="<?php echo $this->baseUrl ?>/login">Login</a> or return to
<a href="<?php echo $this->baseUrl ?>/Front">Front</a> page.</p>
