<?php

/**
 * User Registration View.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 10:29 AM
 */

$this->headTitle('User Registration');

?>

<h1>Register</h1>

<p>By filling out the form below and prior to registering yourself, make sure
you have read the moss.org.mv Privacy Policy and the Disclaimer.</p>

<p>All the fields are <span class="required">required</span>.</p>

<p>Once completed, you should receive and email with instructions on how to
activate your newly created account at moss.org.mv. We look forward to your
participation and support.</p>

<p>You profile avatar is automatically taken from
<a href="http://gravatar.com">gravatar.com</a> which basically matches up with
the email address you provide.</p>

<?php if ($this->form->isErrors()): ?>
<p class="error">Please correct the errors below!</p>
<?php endif; ?>

<?php echo $this->form ?>
