<?php

/**
 * Default index view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tuesday May 26, 2009 07:56 AM
 */

require_once 'markdown/markdown.php';

$this->headLink()->appendStylesheet("{$this->baseUrl}/styles/tabber.css");

?>

<?php if (!empty($this->featuredAnnouncement)): ?>
<?php echo $this->partial('index/featured.phtml', array(
    'featured' => $this->featuredAnnouncement,
    'baseUrl'  => $this->baseUrl)) ?>
<?php endif; ?>

<?php echo $this->partial('index/featured.phtml', array(
    'featured' => $this->featuredNews,
    'baseUrl'  => $this->baseUrl)) ?>

<div class="tabber" style="margin-bottom: 20px;">
    <?php if (isset($this->announcements) && count($this->announcements) > 0): ?>
    <div class="tabbertab" title="Announcements">
        <table border="0" cellspacing="0" cellpadding="2" width="100%" class="listing">
            <?php foreach ($this->announcements as $announcement): ?>
            <tr>
                <td width="120"><?php echo date('M d, Y', strtotime($announcement->date)) ?></td>
                <td><a href="<?php echo $announcement->link  ?>"><?php echo $announcement->title ?></a></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td><a href="#" class="icon icon-feed-14x14" style="margin: 0px;"></a></td>
                    <td align="right" class="mini"><a href="#">More</a></td>
                </tr>
            </tfoot>
        </table>
        
    </div>
    <?php endif; ?>
    <div class="tabbertab" title="News">
        <table border="0" cellspacing="0" cellpadding="2" width="100%" class="listing">
            <?php foreach ($this->news as $news): ?>
            <tr>
                <td width="120"><?php echo date('M d, Y', strtotime($news->date)) ?></td>
                <td><a href="<?php echo $news->link ?>"><?php echo $news->title ?></a></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td><a href="#" class="icon icon-feed-14x14" style="margin: 0px;"></a></td>
                    <td align="right" class="mini"><a href="#">More</a></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<?php echo $this->action('view', 'wiki', 'default', array('name'=>'Front')) ?>

<?php echo $this->inlineScript()->appendFile("{$this->baseUrl}/scripts/tabber-minimized.js") ?>
