<?php

/**
 * Default index view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tuesday May 26, 2009 07:56 AM
 */

require_once 'markdown/markdown.php';

$this->headLink()->appendStylesheet("{$this->baseUrl}/styles/tabber.css");
$this->headScript()->appendScript("var tabberOptions = {manualStartup: true};");
$this->headScript()->appendFile("{$this->baseUrl}/scripts/tabber-minimized.js");

?>

<?php if (!empty($this->featuredAnnouncement)): ?>
<?php echo $this->partial('index/featured.phtml', array(
    'featured' => $this->featuredAnnouncement,
    'baseUrl'  => $this->baseUrl)) ?>
<?php endif; ?>

<?php echo $this->partial('index/featured.phtml', array(
    'featured' => $this->featuredNews,
    'baseUrl'  => $this->baseUrl)) ?>

<div class="tabber" style="margin-bottom: 20px;">
    <?php if (isset($this->announcements) && count($this->announcements) > 0): ?>
    <?php echo $this->partial('index/news.phtml', array(
        'news'    => $this->announcements,
        'baseUrl' => $this->baseUrl,
        'title'   => 'Announcements'))
    ?>
    <?php endif; ?>
    <?php echo $this->partial('index/news.phtml', array(
        'news'    => $this->news,
        'baseUrl' => $this->baseUrl,
        'title'   => 'News'))
    ?>
</div>

<?php echo $this->action('view', 'wiki', 'default', array('name'=>'Front')) ?>

<?php echo $this->inlineScript()->appendScript("tabberAutomatic(tabberOptions)") ?>
