<?php

/**
 * Default sidebar template.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Thursday May 28, 2009 01:16 AM
 */

?>

<?php if ($this->user['authenticated'] == false): ?>
<div id="user-box">
    Member <a href="<?php echo $this->baseUrl ?>/login">Login</a> .
    <a href="<?php echo $this->baseUrl ?>/register">Register</a>
</div>
<?php else: ?>
<?php echo $this->action('sidebar-user', 'index', 'default') ?>
<?php endif; ?>

<div id="search">
	<b>Search</b>
	<form method="get" action="<?php echo $this->baseUrl ?>/search">
	    <input type="text" name="search" size="19" />
	    <input type="submit" name="submit" value="Search" />
	</form>
</div>

<div id="links">
<?php if (isset($this->adminMenus)): ?>
<?php $currentGroup = ''; ?>
<?php foreach ($this->adminMenus as $group => $menu): ?>
<?php if ($currentGroup == ''): ?>
    <h1><?php echo $menu['menuGroupTitle'] ?></h1>
    <ul class="ul">
<?php endif; ?>
<?php $currentGroup = $group ?>
<?php if ($currentGroup != $group && $currentGroup != ''): ?>
    </ul>
    <h1><?php echo $menu['menuGroupTitle'] ?></h1>
    <ul>
<?php endif; ?>
        <li><a href="<?php echo $this->baseUrl ?>/<?php echo str_replace('_', '/', $menu['moduleName']) ?>"><?php echo $menu['moduleTitle'] ?></a></li>
<?php endforeach; ?>
    </ul>
<?php endif; ?>

    <ul class="ul">
        <li><a href="#">Home Page</a></li>
        <li><a href="#">Translation Page</a></li>
        <li><a href="#">Projects Page</a></li>
        <li><a href="#">Launchpad</a></li>
        <li><a href="#">Gnome Danmed Lies</a></li>
    </ul>
</div>
