<?php

/**
 * Default sidebar template.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Thursday May 28, 2009 01:16 AM
 */

?>

<?php if ($this->user['authenticated'] == false): ?>
<div id="user-box">
    Member <a href="<?php echo $this->baseUrl ?>/login">Login</a> .
    <a href="<?php echo $this->baseUrl ?>/register">Register</a>
</div>
<?php else: ?>
<?php echo $this->action('sidebar-user', 'index', 'default') ?>
<?php endif; ?>

<div id="search">
    <form method="get" action="<?php echo $this->baseUrl ?>/search">
        <input type="text" name="search" size="15" />
        <a href="#" class="icon icon-email" title="Search"></a>
    </form>
</div>

<div id="links">
<?php if (isset($this->adminMenus)): ?>
<?php $currentGroup = ''; ?>
<?php foreach ($this->adminMenus as $group => $menu): ?>
<?php if ($currentGroup == ''): ?>
    <h1><?php echo $menu['menuGroupTitle'] ?></h1>
    <ul class="ul">
<?php endif; ?>
<?php $currentGroup = $group ?>
<?php if ($currentGroup != $group && $currentGroup != ''): ?>
    </ul>
    <h1><?php echo $menu['menuGroupTitle'] ?></h1>
    <ul>
<?php endif; ?>
        <li><a href="<?php echo $this->baseUrl ?>/<?php echo str_replace('_', '/', $menu['moduleName']) ?>"><?php echo $menu['moduleTitle'] ?></a></li>
<?php endforeach; ?>
    </ul>
<?php endif; ?>

    <ul class="ul">
        <li><a href="<?php echo $this->baseUrl ?>">Home Page</a></li>
        <li><a href="<?php echo $this->baseUrl ?>/Downloads">Downloads</a></li>
        <li><a href="<?php echo $this->baseUrl ?>/Gallery">Gallery</a></li>
        <li><a href="<?php echo $this->baseUrl ?>/L10n">Localization Project</a></li>
        <li><a href="<?php echo $this->baseUrl ?>/Minutes">Minutes</a></li>
        <li><a href="<?php echo $this->baseUrl ?>/Logo">Logo</a></li>
    </ul>
</div>
