<?php

/**
 * Non existent page view.
 * 
 * This page is displayed if the user requested a page that is non existent.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 04:17 AM
 */

?>

<h1>Page Does Not Exist</h1>

<p>The page <a href="#" class="non-existent"><?php echo $this->name ?></a> requested, is a non existent page. Click on
the link to create a new page with the name, or below is a list of suggestions
of similar pages.</p>

<p>> list of similar pages (fulltext matches)</p>
