<?php

/**
 * Default sidebar template.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Thursday May 28, 2009 01:16 AM
 */

?>

<div id="search">
	<b>Search</b>
	<form method="get" action="<?php echo $this->baseUrl ?>/search">
	    <input type="text" name="search" size="19" />
	    <input type="submit" name="submit" value="Search" />
	</form>
</div>

<p>Member <a href="#">Login</a> / <a href="#">Register</a><p>

<div id="links">
    <ul class="ul">
        <li><a href="#">Home Page</a></li>
        <li><a href="#">Translation Page</a></li>
        <li><a href="#">Projects Page</a></li>
        <li><a href="#">Launchpad</a></li>
        <li><a href="#">Gnome Danmed Lies</a></li>
    </ul>
</div>