<?php

/**
 * Partial User Box view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 07:22 AM
 */

?>

<div id="user-box">
    <div id="sb-ub-i">
        <?php
        $email = $this->userns->email;
        $size  = 30;
        $default = 'http://github.com/images/gravatars/gravatar-30.png';
        $gravUrl = 'http://www.gravatar.com/avatar.php?gravatar_id='.md5(strtolower($email)).'&default='.$default.'&size='.$size;
        ?>
        <img src="<?php echo $gravUrl ?>" width="30" height="30" border="0" />
    </div>
    <div id="sb-ub-c">
        <?php echo $this->userns->name ?><br />
        <a href="<?php echo $this->baseUrl ?>/profile">Profile</a> . 
        <a href="<?php echo $this->baseUrl ?>/logout">Logout</a>
    </div>
    <div style="clear: both;"></div>
</div>
