<?php

/**
 * Index view for Contact controller. Displays the contact form.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Jul 27, 2009 12:55 AM
 */

?>

<h1>Contact Us</h1>

<p>Thank you for your interest in contacting us. Fill in the form below with
the required details and submit the form. We will get back to you soon.</p>

<?php if ($this->form->isErrors()): ?>
<div id="messages">There are errors in the Contact Us form. Please correct them
and submit again.</div>
<?php endif; ?>

<?php echo $this->form->render() ?>
