<?php

/**
 * Common header view script for profile views.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Wed Jul 22, 2009 02:52 AM
 */

?>

<div id="profile">
    <div id="avatar">
        <?php 
        $config = Zend_Registry::get('config');
        $email = $this->user['email'];
        $size  = 50;
        $default = "http://{$config->app->hostname}{$this->baseUrl}/pix/gravatar-50.png";
        $gravUrl = 'http://www.gravatar.com/avatar.php?gravatar_id='.md5(strtolower($email)).'&default='.$default.'&size='.$size;        
        ?>
        <img src="<?php echo $gravUrl ?>" border="0" width="50" height="50" />
    </div>
    <div id="name"><h1><?php echo ($this->user['name'] != '') ? $this->user['name'] : $this->user['userId'] ?></h1></div>
    <div style="clear: both;"></div>
</div>
