<?php

/**
 * Main layout.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tuesday May 26, 2009 07:34 AM
 */

echo $this->doctype('XHTML1_STRICT')

?>

<html>
<head>
    <base href="<?php echo $this->baseUrl ?>" />
    <?php echo $this->headTitle() ?>
    
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/styles.css" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>

</head>

<body>
<div id="header">
    <div id="content">
        <div id="title">MOSS</div>
        <ul id="links">
            <li><a href="<?php echo $this->baseUrl ?>/Front">Home</a>
            <li><a href="<?php echo $this->baseUrl ?>/About">About</a>
            <li><a href="<?php echo $this->baseUrl ?>/Projects">Projects</a>
            <li><a href="<?php echo $this->baseUrl ?>/FAQ">FAQ</a>
            <li><a href="<?php echo $this->baseUrl ?>/contact">Contact</a>
        </ul>
        <div style="clear: both;"></div>
    </div>
</div>

<div id="menu">
</div>

<div id="main">
    <div id="body">
        <div id="content">
            <?php if (isset($this->messages) && count($this->messages) == 1): ?>
            <div id="messages">
            <?php echo $this->messages[0] ?>
            </div>
            <?php endif; ?>
            <?php echo $this->layout()->content ?>
        </div>
        <div id="sidebar">
        <?php echo $this->layout()->sidebar ?>
        <?php if ($this->user['class'] == 'Administrator'): ?>
            <?php echo $this->action('sidebar', 'index', 'admin') ?>
        <?php endif; ?>
        </div>
        <div style="clear: both;"></div>
    </div>
</div>

<div id="menu-bottom">
    <ul id="links">
        <li><a href="#">Top</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Policies</a></li>
        <li><a href="#">Privacy</a></li>
        <li><a href="#">Press</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="#">Sitemap</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
</div>

<div id="footer">
    <div id="text">
        All Rights Reserved. Licensed under a
        <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share Alike 3.0 Unported License</a>.
    </div>
</div>
</body>
</html>
