<?php

/**
 * User's listing and administration view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Aug 24, 2009 05:13 AM
 */

$this->headTitle('Manage Users');

?>

<h1>Manage Users</h1>

<?php echo $this->action('header', 'users', 'admin', $this->params) ?>

<?php if (isset($this->paginator) && $this->paginator->count() > 0): ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'users/paginator.phtml', $this->params) ?>

<div id="submenu">
    <a href="<?php echo $this->baseUrl ?>/admin/users/exportcsv" class="icon icon-csv">Export to CSV</a>
</div>

<table border="0" cellspacing="0" cellpadding="4" class="border" width="100%" id="tblUsers">
    <thead>
        <tr>
            <td>Username</td>
            <td>Name</td>
            <td width="100">Last Seen</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $user): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl ?>/admin/users/view/userId/<?php echo $user['userId'] ?>"><?php echo $user['userId'] ?></a></td>
            <td><?php echo $user['name'] ?></td>
            <td><?php echo date('d M, Y', strtotime($user['dateLastLogin'])) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div id="messages">There are no records available for the selected filter.</div>
<?php endif; ?>
