<?php

/**
 * Admin user information view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tue Aug 25, 2009 07:31 AM
 */

$this->headTitle('Manage - '.$this->user->getUserId());

?>

<h1>Manage User</h1>

<?php echo $this->action('header', 'users', 'admin') ?>

<?php echo $this->render('users/actions.phtml') ?>

<table border="0" cellspacing="0" cellpadding="4" class="view">
    <tr>
        <th>Username:</th>
        <td><?php echo $this->user->getUserId() ?></td>
    </tr>
    <tr>
        <th>Name:</th>
        <td><?php echo $this->user->getName() ?></td>
    </tr>
    <tr>
        <th>Email:</th>
        <td><?php echo $this->user->getEmail() ?></td>
    </tr>
    <tr>
        <th>Membership Type:</th>
        <td><?php echo $this->user->getMemberType() ?></td>
    </tr>
    <tr>
        <th>Primary Group:</th>
        <td><?php echo $this->user->getPrimaryGroup() ?></td>
    </tr>
    <tr>
        <th>Website:</th>
        <td><?php echo $this->user->getWebsite() ?></td>
    </tr>
    <tr>
        <th>Company:</th>
        <td><?php echo $this->user->getCompany() ?></td>
    </tr>
    <tr>
        <th>Location:</th>
        <td><?php echo $this->user->getLocation() ?></td>
    </tr>
    <tr>
        <th>Registered:</th>
        <td><?php echo ($this->user->getDateRegistered() != '') ? date('r', strtotime($this->user->getDateRegistered())) : '' ?></td>
    </tr>
    <tr>
        <th>Last Seen:</th>
        <td><?php echo ($this->user->getDateLastLogin() != '') ? date('r', strtotime($this->user->getDateLastLogin())) : '' ?></td>
    </tr>
    <tr>
        <th>Active:</th>
        <td><?php echo $this->user->getActive() ?></td>
    </tr>
    <tr>
        <th>Reset:</th>
        <td><?php echo $this->user->getReset() ?></td>
    </tr>
    <tr>
        <th>Disabled:</th>
        <td><?php echo $this->user->getDisabled() ?></td>
    </tr>
</table>