<?php

/**
 * Projects listing view. Shows public/private/restricted projects the user is
 * entitled to see. Displays generic information about a project and other
 * resources.
 *
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Feb 15, 2010 10:20 PM
 */

?>

<h1>Projects</h1>

<table border="0" cellspacing="0" cellpadding="4" width="100%" class="border">
    <thead>
        <tr>
            <td>Title</td>
            <td>Created By</td>
            <td>Created On</td>
            <td>Due</td>
            <td>Status</td>
            <td>Progress</td>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->projects as $project): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl ?>/p/<?php echo $project['name'] ?>"><?php echo $project['title'] ?></a></td>
            <td><?php echo $project['uname'] ?></td>
            <td><?php echo date('M d, Y', strtotime($project['dateCreated'])) ?></td>
            <td><?php echo ($project['dateEnd'] != null) ? date('M d, Y', strtotime($project['dateEnd'])) : '-' ?></td>
            <td><?php echo $project['status'] ?></td>
            <td>-</td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
