<?php

/**
 * Wiki page footer element.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Jun 01, 2009 12:55 PM
 */

?>

<div id="wiki-info-box-footer">
    Created: <a href="<?php echo $this->baseUrl ?>/<?php echo $this->page->createdBy ?>"><?php echo $this->page->findParentRow('Default_Model_DbTable_Users', 'CreatedBy')->name ?></a>
    on <?php echo date('M d, Y H:i', strtotime($this->page->dateCreated)) ?>,
    Modified: <a href="<?php echo $this->baseUrl ?>/<?php echo $this->page->modifiedBy ?>"><?php echo $this->page->findParentRow('Default_Model_DbTable_Users', 'ModifiedBy')->name ?></a>
    on <?php echo date('M d, Y H:i', strtotime($this->page->dateModified)) ?>
</div>
