<?php

/**
 * Wiki page header element.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Jun 01, 2009 12:08 PM
 */
?>

<div id="wiki-info-box">
    <ul class="ul">
        <?php if ($this->user['authenticated'] == true): ?>
        <li><a href="<?php echo $this->baseUrl.'/'.$this->page->name ?>/edit" class="link-icon wiki-edit">Edit</a></li>
        <?php endif; ?>
    </li>
</div>
