<?php

/**
 * Create new Wiki Page View.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 06:01 AM
 */

$this->headTitle($this->name);
$this->headTitle('New');

?>

<h1>Create New Page</h1>

<p>You're creating a new Page titled <b><?php echo $this->name ?></b></p>

<form method="post" action="<?php echo $this->baseUrl ?>/wiki/new">
    <table border="0" cellspacing="0" cellpadding="4" width="100%">
        <tbody>
            <tr>
                <th>Name:</th>
                <td><input type="text" name="name" size="50" maxlength="50" value="<?php echo $this->name ?>" class="full-width" /></td>
            </tr>
            <tr>
                <th>Title:</th>
                <td><input type="text" name="title" size="50" class="full-width" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <textarea name="body" class="ta-editor"></textarea>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" name="preview" value="Preview" class="default" />
                    <input type="submit" name="save" value="Save" />
                </td>
            </tr>
        </tfoot>
    </table>
</form>
