<?php

/**
 * Create new Wiki Page View.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun May 31, 2009 06:01 AM
 */

$this->headTitle($this->name);
$this->headTitle('New');

?>

<h1>Create New Page</h1>

<p>You're creating a new Page titled <b><?php echo $this->name ?></b></p>

<form method="post" action="">
    <table border="0" cellspacing="0" cellpadding="4" width="100%">
        <tbody>
            <tr>
                <th>Name:</th>
                <td><input type="text" name="name" size="50" maxlength="50" value="<?php echo $this->name ?>" class="full-width" /></td>
            </tr>
            <tr>
                <th>Title:</th>
                <td><input type="text" name="title" size="50" class="full-width" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <textarea name="body" class="ta-editor"></textarea>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" name="preview" value="Preview" class="default" />
                    <input type="submit" name="save" value="Save" />
                </td>
            </tr>
        </tfoot>
    </table>
</form>

<h2>Markdown Syntax</h2>

<small>Taken from the Markdown Wikipedia page.</small>

<h3>Paragraphs</h3>

<p>A paragraph is one or more consecutive lines of text separated by one or more
blank lines. Normal paragraphs should not be indented with spaces or tabs:</p>

<pre>This is a paragraph. It has two sentences.
This is another paragraph. It also has two sentences.</pre>

<h3>Line Return</h3>

<p>Line breaks inserted in the text are removed from the final result: the web
browser is in charge of breaking the lines depending of the available space. To
force a line break, insert two spaces at the end of the line.</p>

<h3>Emphasized text</h3>

<pre>*emphasis* (e.g., italics)</pre>
<pre>**strong emphasis** (e.g., boldface)</pre>

<h3>Code</h3>

<pre>`code`</pre>

<h3>Lists</h3>

<pre>- An item in a bulleted (unordered) list
- Another item in a bulleted list</pre>

<pre>1. An item in an enumerated (ordered) list
2. Another item in an enumerated list</pre>

<h3>Headings</h3>

<p>HTML headings are produced by placing a number of hashes before the header
text corresponding to the level of heading desired (HTML offers six levels of
headings), like so:</p>

<pre># First-level heading</pre>
<pre>#### Fourth-level heading</pre>

<p>The first two heading levels also have an alternate syntax:</p>

<pre>First-level heading
===================</pre>
<pre>Second-level heading
--------------------</pre>

<h3>Blockquotes</h3>

<pre>> This text will be enclosed in an HTML blockquote element.</pre>

<h3>Links</h3>

<pre>[link text here](link.address.here "link title here")</pre>

<h3>Images</h3>

<pre>![Alt text here](Image URL here "Image title here")</pre>

<h3>Horizontal Rules</h3>

<p>Horizontal rules are created by placing three or more hyphens, asterisks, or
underscores on a line by themselves. You may use spaces between the hyphens or 
asterisks. Each of the following lines will produce a horizontal rule:</p>

<pre>* * *
***
*****
- - -
---------------------------------------</pre>
