<?php

/**
 * Display page revisions view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Tue Jun 02, 2009 03:20 AM
 */

$this->headTitle($this->page->title);
$this->headTitle('Revisions');
$this->headScript()->appendFile($this->baseUrl.'/scripts/prototype.js');
$this->headScript()->appendFile($this->baseUrl.'/scripts/jsdiff.js');

?>

<?php echo $this->render('wiki/header.phtml') ?>

<h1>Page Revision</h1>

<p>Displaying page revision at 
<?php echo date('r', strtotime($this->pageRevision['timestamp'])) ?> 
for <?php echo $this->page->title ?>.</p>

<div id="diff-revs" class="pre"><?php echo $this->diff ?></div>

<?php echo $this->render('wiki/footer.phtml') ?>

<?php if ($this->user['authenticated'] == true &&
        $this->acl->isAllowed($this->user['userId'], 'default_wiki', 'revert')): ?>
<form method="post" action="">
    <input type="submit" id="btnRevert" name="revert" value="Revert" />
    Revert to this version.
</form>

<script type="text/javascript">
$('btnRevert').observe('click', function(e) {
    e.stop();
    if (confirm('Sure to Revert to this Version?')) {
        this.form.submit();
    }
});
</script>
<?php endif; ?>
