<?php

/**
 * Display a selected users profile information. Just the basic information.
 * Based on the user preferences, some of the information has to be hidden.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Sun Jun 7, 2009 07:32 AM
 */

$this->headTitle($this->profile['name']);

?>

<?php echo $this->partial('profile/header.phtml', array('user'=>$this->profile, 'baseUrl'=>$this->baseUrl)) ?>

<div id="profile-box">
    <table border="0" cellspacing="0" cellpadding="2">
        <tr>
            <th>Name:</th>
            <td><?php echo $this->profile['name'] ?></td>
        </tr>
        <tr>
            <th>Member Type:</th>
            <td><?php echo $this->profile['memberType'] ?></td>
        </tr>
        <?php if ($this->profile['website'] != ''): ?>
        <tr>
            <th>Website:</th>
            <td><?php if ($this->profile['website'] != ''): ?><a href="http://<?php echo ltrim($this->profile['website'], 'http://') ?>"><?php echo $this->profile['website'] ?></a><?php endif; ?>&nbsp;</td>
        </tr>
        <?php endif; ?>
        <?php if ($this->profile['company'] != ''): ?>
        <tr>
            <th>Company:</th>
            <td><?php echo $this->profile['company'] ?></td>
        </tr>
        <?php endif; ?>
        <?php if ($this->profile['location'] != ''): ?>
        <tr>
            <th>Location:</th>
            <td><?php echo stripslashes($this->profile['location']) ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <th>Member Since:</th>
            <td><?php echo date('D, d M Y', strtotime($this->profile['dateRegistered'])) ?></td>
        </tr>
        <tr>
            <th>Last Seen:</th>
            <td><?php echo date('D, d M Y', strtotime($this->profile['dateLastLogin'])) ?></td>
        </tr>
    </table>
</div>
