<?php

/**
 * Wiki page history view.
 * 
 * @author  Inash Zubair <inash@leptone.com>
 * @created Mon Jun 01, 2009 11:18 AM
 */

$this->headTitle('Page History');
$this->headTitle($this->page->title);

?>

<?php echo $this->render('wiki/header.phtml') ?>

<h1>Page History</h1>
<form>
    <table border="0" cellspacing="0" cellpadding="4" id="tbl-wiki-history" class="border" width="640">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Timestamp</th>
                <th>User</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->history as $cnt => $history): ?>
            <tr<?php if ($this->page->pageRevisionId == $history['pageRevisionId']): ?> class="highlight"<?php endif; ?>>
                <td width="22">
	                <?php if ($this->userns->authenticated): ?>
	                <input type="radio" name="revertTo" value="<?php echo $history['pageRevisionId'] ?>" />
	                <?php endif; ?>
	            </td>
                <td>
                    <?php if ($cnt+1 < count($this->history)): ?>
                    <a href="<?php echo $this->baseUrl.'/'.$this->page->title ?>/revision/<?php echo $history['pageRevisionId'] ?>">
                    <?php echo date('Y-m-d H:i O', strtotime($history['timestamp'])) ?>
                    </a>
                    <?php else: ?>
                    <?php echo date('Y-m-d H:i O', strtotime($history['timestamp'])) ?>
                    <?php endif; ?>
                    <?php if ($this->page->pageRevisionId == $history['pageRevisionId']): ?>
                    (Current)
                    <?php endif; ?>
                </td>
                <td><a href="<?php echo $this->baseUrl.'/'.$history['userId'] ?>"><?php echo $history['name'] ?></a></td>
                <td><?php echo $history['summary'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php if ($this->userns->authenticated): ?>
        <tfoot>
            <tr>
                <td colspan="4">
                    <input type="submit" name="revert" value="Revert" />
                    <span class="info">Revert to the above selected revision.</span>
                </td>
            </tr>
        </tfoot>
        <?php endif; ?>
    </table>
</form>

<?php echo $this->render('wiki/footer.phtml') ?>
